services:
  cloud-storage:
    # GCSç”¨
    container_name: test-cloud-storage
    image: fsouza/fake-gcs-server:1.43.0
    tty: true
    ports:
      - "4443:4443"
    volumes:
      - ./config/gcp/cloud-storage/data:/data/test
      - ./config/gcp/cloud-storage/storage:/storage
    command: -scheme http -public-host ${URL:-localhost}:4443
